NextCenturyCorporation/AIDA-Interchange-Format

- src/test/resources/edu/isi/gaia/images_to_aif_sample.txt
This passes the ImagesToAIFTest.java, since there is a new requirement to have a colon with something before it.
> Change resource example to pass ImagesToAIFTest.java

- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/java/edu/isi/gaia/ValidateAIF.kt
This should make testing run faster while the NIST servers are down
> AIDA-514: Add imports to OntModel that we're already reading in

- README.md
- pom.xml
- sample_params/validate.common_corpus.single.params
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
The new AIF validator.  The README shows most of the changes.  The [Confluence page](https://nextcentury.atlassian.net/wiki/spaces/AIDA/pages/500859060/AIF+Validator) is still pretty much up-to-date.
NOTES:
* At present, the --nist switch is not supported and will cause the program to exit with an error.  It will start working once [AIDA-287](https://nextcentury.atlassian.net/browse/AIDA-287) (i.e., enforce NIST SHACL) is merged into the tree.
* The README has a section called "Validation duration" but none of the execution times (durations) are included at the moment.
* Validation with the --program switch hasn't been tested as I didn't have any KBs using that ontology.  I'll be working on this imminently.
A lot of time was spent testing the processing of arguments, but reviewers will …
> Aida 467: the AIF Validator

- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
Most of this was actually previously fixed by AIDA-287 (specifically, the copy-paste error in which `markName` was called repeatedly on the `presidentUSA` entity rather than each new entity that is created).  What was performed here is varying the confidences as per AIDA-538, and updating the [Example Requests](https://nextcentury.atlassian.net/wiki/spaces/AIDAC/pages/334069840/Example+Requests) Confluence page.
To test this, you could take the code from the updated Confluence page and either inspect it, validate it, check that more than `presidentUSA` is included, or otherwise ensure that what AIDA-538 asks has been accomplished.  You could also go back and look at the diffs from AIDA-287 where this was substantially fixed.
> AIDA-538: Fix createHierarchicalCluster() example

- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/resources/com/ncc/aif/aida_ontology.shacl
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
- src/test/java/com/ncc/aif/ScalingTest.java
Changes for [AIDA-554](https://nextcentury.atlassian.net/browse/AIDA-554):
- Removed reference to an undefined rule from AIF (this cased `pySHACL` to report an invalid shape);
- Added loaded imports to Data Graph (file to be validated)-- this was required in some cases for Jena to load the KB;
- Fixed the AIF `ScalingTest` to generate valid (unrestricted) AIF;
- Added functionality to the AIF `ScalingTest` so that it can generate (and optionally validate) arbitrarily large KBs.
- Wrote an associated [Confluence page](https://nextcentury.atlassian.net/wiki/spaces/AIDA/pages/510558318/AIF+Validator+Performance) with embedded Excel file to show validator timing results.
To test this PR, consider exercising the `ScalingTest` and running some generated KBs against the AIF Validator.  Depending …
> Aida 554: Run validator performance benchmarks on HAL 2.0

- src/main/java/com/ncc/aif/AIFUtils.java
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/resources/com/ncc/aif/aida_ontology.shacl
- src/main/resources/com/ncc/aif/restricted_aif.shacl
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
Work performed:
- Added the restriction to the restricted AIF SHACL file.
- Added `JustifyTypeAssertions` valid and invalid test to `NISTExamples`.
- Retrofitted other NIST tests (both valid and invalid) as necessary so the valid tests stayed valid and the invalid tests only failed for the "right" reasons-- the reasons that they are testing.
- Since I visited every test, in some cases I tweaked the test, most notably relying on `setup()` for the `EverythingClustered.valid()` test and I believe fixing `RestrictJustification.invalid()` so it doesn't also fail because of the "Exactly 1 or 2 contained justifications required for an edge" restriction...unless the intention was to remove the EdgeJustificationLimit class?  Please verify this action was correct.
- Did a tiny bit of cleanup. …
> Aida 667: type assertions must be justified

- src/main/java/com/ncc/aif/AIFUtils.java
- src/main/resources/com/ncc/aif/ontologies/InterchangeOntology
- src/main/resources/com/ncc/aif/ontologies/README.md
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
Work performed:
Reflect the fact that relations can be added to clusters in InterchangeOntology, ontology README, and AIFUtils Javadoc.
Deprecate AIFUtils.makeRelationInEventForm() and update examples not to use it.
I hedged my bets a bit in the README by saying "should be able to" because we don't actually use it / test it.  Should I make it stronger by saying it's "unsupported" or something?  Do we support it?
> AIDA 704:  Clusters must be able to contain Relations

- README.md
- src/main/java/com/ncc/aif/AIFUtils.java
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/resources/com/ncc/aif/aida_ontology.shacl
Updated that --ldc now uses LDCOntology, not SeedlingOntology.
Updated some references to Seedling / LDC.
> AIDA-612:  Migrate validator from Seedling to LDC

- README.md
- src/main/java/com/ncc/aif/ValidateAIF.java
Check file size for TA3 output, also refactored main method a bit.  I'm open to more refactoring, breaking up blocks of code into private methods.  Let me know.
To test, create a file about 5MB (it doesn't have to be a valid ttl) and invoke the validator (via  command line or IntelliJ) with command-line options of `--ldc -f <filename>.ttl --nist-ta3`
Tweak the file to be slightly more or less than 5MB and make sure the validator rejects the file that is > 5M.
Also, test some other combinations of valid and invalid kbs.  Note that --ldc now uses the LDC ontology, not Seedling.  But you can use an essentially empty file as a valid KB.
> AIDA-703:  Check file size for TA3 output

- pom.xml
This fixes a deprecated Kotlin standard library dependency (used by the ColdStart converter)
> Upgrade to Kotlin 1.3

- src/test/java/com/ncc/aif/ScalingTest.java
Updated the ScalingTest to use LDC Ontology and generate valid or invalid restricted AIF.
To test, generate valid and invalid files and validate with the AIF validator (saving invalid results to a file).  Inspect the report from the invalid file and ensure that types and numbers of violations are in line with expectations.  Note that validation time has increased significantly with the latest NIST restrictions.  On my laptop, validating a model with 1000 entities and 300 events took 26 minutes.
I'm hoping that as part of the review process, we can come up with better/reasonable frequency constants (FREQ_*) for each of the restrictions.  I have set them all to a "default" value of 0.3.  Note that this number doesn't necessarily mean "30% of the time, the given restriction will be …
> AIDA-688:  Update ScalingTest to generate valid/invalid LDC restricted AIF

- README.md
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
- src/test/java/com/ncc/aif/ScalingTest.java
Validator accepts a `-o` switch to create an output file for each file that failed validation (e.g., `foobar.ttl` results in `foobar-results.txt`).  Validator no longer dumps report by default, but it makes the validation report model available to the client.  Updated `README` and `ExamplesAndValidationTests.java`.  Will need to update [AIF Validator page](https://nextcentury.atlassian.net/wiki/spaces/AIDAC/pages/505053485/AIF+Validator) after merge.
To test, use the validator with and without `-o` on files (`-f`) and directories (`-d`).
> Aida 711: Add output options to validator

- src/main/java/com/ncc/aif/ValidateAIF.java
A profiling feature was added to the AIF validator, available via the undocumented `-p` switch, that collects query performance statistics gathered by TopBraid's `ExecStatisticsManager` class and reports on slow queries.  There are two variants of the statistics collector:
- The default `StatsCollector`, which collects all slow query information after validation is complete and dumps it to a file, and
A `ProgressiveStatsCollector` which progressively outputs slow query data to `stdout`, and can also dump it to a file.
~Right now, the only way to change the profiler is to tweak the validator code, by changing the instantiation from `StatsCollector` to `ProgressiveStatsCollector`.~
Also, a new section has been added to the [AIF Validator …
> Aida 733: Identify slow SHACL rules

- pom.xml
- Updated various jar versions to latest.
- Fixed Kotlin warnings for [PR-177](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/177).
- Did *not* update Jena because it breaks our TDB tests, and appears to have something to do with mixing Jena versions (3.11 in AIF and 3.7 in TopBraid shacl jar)
- Did *not* update JUnit/surefire because we get warnings for the `junit-platform-surefire-provider` being deprecated in JUnit platform 1.3.  "Please use Maven Surefire’s native support instead."  Maybe someday...
> AIDA-802: Update jar versions

- src/main/resources/com/ncc/aif/aida_ontology.shacl
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
- Fixed AIF SHACL.
- Added justification to `createEventWithLDCTime()` test.
This PR is just for master.  Incorporation into the v1.0.x branch will occur in a separate [Jira task](https://nextcentury.atlassian.net/browse/AIDA-817) with its own associated PR.
> AIDA-808:  Fix LDCTimeShape bug

- src/main/resources/com/ncc/aif/restricted_aif.shacl
Moved `aida:RestrictCompoundJustificationPropertyShape` to the combined `aida:EventRelationShape`.
Breaking up the test will be handled in [AIDA-813](https://nextcentury.atlassian.net/browse/AIDA-813) and/or [AIDA-796](https://nextcentury.atlassian.net/browse/AIDA-796).
> AIDA-811: Fix NIST restriction 4.3.6.3

- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/resources/com/ncc/aif/aida_ontology.shacl
- src/main/resources/com/ncc/aif/restricted_hypothesis_aif.shacl
- src/test/java/com/ncc/aif/NistTA3ExamplesAndValidationTest.java
Use default Jena models instead of OntModel.
Add SameAsCluster to subgraphContains.
Add KEsInModelMustBeReferencedByHypothesis.validWithClusterAndMembership test.
> AIDA-827: Allow clusters to be in hypothesis:

- scripts/aida_m18_submission_checker.py
- scripts/m18_submission_checker/README.md
- scripts/m18_submission_checker/aida_m18_submission_checker.py
Linked to ticket AIDA-871
This is designed to be a standalone python3 script that can be sent out to performers so that they can run it on their archives and check if their archive is submit ready. Submit ready means that the archive is structured properly for the AIF M18 batch validation process. 
- Ensure that the task type was determined correctly; 
- that the output is clear as to which task type the archive was checked for; 
- that the program does not raise false positives in where it states an archive is submit ready when it should not be. 
`python3 aida_m18_submission_checker.py <path/to/archive>`
> Adding m18 submission checker script

- src/test/java/com/ncc/aif/ScalingTest.java
Added `JustificationSourceAndSourceDocument` to the `NIST_RESTRICTION` list, and randomly either add or don't add the source document to the justification.
> Aida 884: Update ScalingTest's ability to create valid KBs

- README.md
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/java/com/ncc/aif/ValidateAIFCli.java
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
- Added `--disk` option to enable disk-based model
- Attempted to clean up as much as possible from the HD on both Linux and Windows
- Tested in conjunction with `--abort`, `-p`, `--p2`, `--pm`, and `-t`.
- Summary of execution results with and without disk-based model available [on Confluence](https://nextcentury.atlassian.net/wiki/spaces/AIDA/pages/510558318/AIF+Validator+Performance) (look for reference to AIDA-735).
> Aida 735: Test using the TDB model for large TA2 KBs

- python/aida_interchange/LDCTimeComponent.py
- python/tests/Examples.py
Incorporated AIDA-889 (Python LDCTime typo fix) into v1.0.x.
> AIDA-890:  Incorporate AIDA-889 into v1.0.x

- python/tests/Examples.py
Fixed examples.py reference to the typo fix in AIDA-889.
> Updated examples for LDCTimeType Enum fix.

- README.md
- src/main/java/com/ncc/aif/ThreadedValidationEngine.java
- src/main/java/com/ncc/aif/ValidateAIF.java
- src/main/java/com/ncc/aif/ValidateAIFCli.java
- src/test/java/com/ncc/aif/ValidateCLITest.java
The `--depth` option performs a “shallow” validation in which each SHACL rule (shape) only considers a subset of its target nodes.
Notes:
- Specifying `--depth=-1` doesn't get rejected and performs a regular validation.  This is a picocli quirk as -1 is the "default" value.  The same thing happens with `--abort`.  Maybe I'll fix this...thoughts?
--> **Update:  fixed this.**
- I left in a line of debugging so you can see shallow validation "in action."  Obviously I'll remove it prior to merge.
- I'm not sure what a good default depth value is.  Thoughts?
- Test in combination with `--abort`, `-p`, `--p2`, `--disk`, and whatever other options you see fit.
> AIDA-888:  shallow validation

- README.md
- pom.xml
Removed extraJvmArguments from pom;
Documented memory considerations in README;
Added a section to README for shallow validation (since it was lacking).
> AIDA-904: Remove JVM RAM specification from POM

- python/aida_interchange/aifutils.py
- src/main/java/com/ncc/aif/AIFUtils.java
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
Closes [PR#228](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/228) and Issue #227.
Work performed:
- Added optional URIs to Java justification APIs and to Python & Java mark_as_possible_cluster_member
- Added Java tests for all optional URIs
- A little bit of Python AIF doc cleanup
To test Java changes, create Java examples by setting `DUMP_ALWAYS` and `DUMP_TO_FILE` in `ExamplesAndValidationTest.java` and inspect generated AIF.
> AIDA-893: add optional URIs to certain Python/Java APIs

- python/aida_interchange/aifutils.py
- src/main/java/com/ncc/aif/AIFUtils.java
- src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
Incorporated AIDA-893 (optional URIs to certain API) into v1.0.x release.
You may find it useful to compare with [AIDA-893 changed files](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/249/files) to see how the changes were incorporated.
Note I also incorporated a small fix to `AIFUtils.markLDCTime()` that was made as part of AIDA-795 (multithreaded validator).
> AIDA-894: incorporate AIDA-893 into v1.0.x

- python/aida_interchange/aifutils.py
- python/aida_interchange/ldc_time_component.py
There were minor space differences that didn't get back into master.
$ git checkout develop
$ git diff tag/v1.0.4
- see no differences
$ git diff master
- see minor space differences
This PR updates master to match v1.0.4
> minor space differences between master and tag/v1.0.4

- FAQ.md
- README.md
- java/README.md
- java/pom.xml
- python/setup.py
- Upgraded the com.fasterxml.jackson libraries to version 2.10.0 to address potential vulnerability.
- Changed AIF version to 1.0.5 in both Java and Python versions
- Updated all documentation to point to AIF 1.0.5
**After this gets merged into master we will need to tag it as release 1.0.5**
> AIDA-1114 Hotfix

- FAQ.md
- java/pom.xml
**NOTE: This PR should not be merged into `develop` until [AIDA-930 / PR#305](https://github.com/NextCenturyCorporation/VERDI/pull/305) (Upgrade VERDI to later Java version) is approved.**
Background, process, and discussion of updating dependencies are all documented in the [Upgrading Java in AIDA](https://nextcentury.atlassian.net/wiki/spaces/AIDA/pages/628228337/Upgrading+Java+in+AIDA) Confluence page.
Also note that the build currently targets release 11 (JDK 11).  The AIDA Architecture Working Group meeting suggested that people didn't have a problem with us requiring a post-JDK8 version of Java.
> Aida 525: Update AIF to Java 11

- java/README.md
Added documentation about Java 11 requirement.
I'm re-testing the build with Java 8 section now on Linux, but wanted to get this into code review.
> AIDA-1357: Documented Java 11 requirement

- java/src/main/java/com/ncc/aif/AIFUtils.java
- java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
The example test added in this branch generates the AIF shown on the "Support for Composite Cluster Member Information" to be made public to teams after review.
Note - I set the DUMP_ALWAYS and DUMP_TO_FILE constants to true, so you can easily find this generated example in java/target/test-dump-output/ExamplesAndValidationTest_ValidExamples_createEventsWithLDCTimeRanges.ttl
Before it gets merged in, these constants should be changed back to false.
> AIDA-1372: Add example to generate LDCTime ranges

- docker/aif-validator/.gitignore
- docker/aif-validator/Dockerfile
- docker/aif-validator/README.md
- docker/aif-validator/build.sh.example
- docker/aif-validator/run.sh.example
- docker/aif-validator/scripts/main.py
This AIF validator container is adapted from the existing batch-init / batch-single containers but is meant to be run locally (i.e., not in AWS Batch).  This is intended to be inserted into the evaluation pipeline after an algorithm runs and before the finalizer, however, I think there may be stand-alone uses for it.
Currently, all parameters are passed in as environment variables.  Arguably, passing them in as command-line variables to the ENTRYPOINT may be (more? or less?) useful.  
Feedback on any of this is welcome.
> AIDA-1459: Initial commit standalone AIF validator container image

- java/src/main/resources/com/ncc/aif/restricted_claimframe_aif.shacl
Added shacl support for  2.4 #16. The graph of Associated KEs must have at least one event cluster or relation cluster with at least one edge.
> added - Associated KEs must have cluster >=1
