src/main/java/edu/isi/gaia/ColdStart2AidaInterchange.kt
src/main/java/edu/isi/gaia/ColdStartKB.kt

[WIP] CS2Aif: fix bug with nominals and pronouns in hasName

---

src/main/resources/edu/isi/gaia/aida_ontology.shacl

This is a requirement by NIST.

Allow relations to be clustered

---

README.md

Updated reference to ontology file.

---

python/aida_interchange/aifutils.py
python/tests/Examples.py
setup.py

Make Python code install as a module

---

src/main/java/edu/isi/gaia/ColdStart2AidaInterchange.kt

Closes https://github.com/isi-vista/aida-tools/issues/146

Use .ttl extension for CS converter output

---

src/main/resources/com/ncc/aif/restricted_aif.shacl
src/test/java/com/ncc/aif/ExamplesAndValidationTest.java

Add restriction to force 1 confidence on linkAssertion.
Add examples

AIDA-758: LinkAssertion restrictions.

---

src/main/java/edu/isi/gaia/ColdStartKB.kt

By default, these confidences are now required.
You can relax this requirement by setting requireLinkConfidences=False
on ColdStartKBLoader, although we currently do not expose this
in the ColdStart converter interface.
Closes #180

ColdStart KB now parses link assertion confidences.

---

src/main/java/com/ncc/aif/AidaAnnotationOntology.java
src/main/resources/com/ncc/aif/ontologies/InterchangeOntology
src/test/java/com/ncc/aif/OntologyTest.java

Fix copy+paste error
Add classes and properties
Add test to help avoid this in the future

AIDA-793: Add informativeJustification and ldcTime to InterchangeOntology

---

pom.xml

Bumped version number to 1.0.0

---

pom.xml

Set up snapshot for the next release

Snapshot for next release 1.1.0

---

pom.xml
src/main/resources/com/ncc/aif/aida_ontology.shacl
src/test/java/com/ncc/aif/ExamplesAndValidationTest.java

- Set pom version to 1.0.1-SNAPSHOT
- Incorporated AIDA-808 (LDCTime fix) into v1.0 release

AIDA-817 (incorporate AIDA-808 into v1.0)

---

README.md
src/main/resources/com/ncc/aif/aida_ontology.shacl
src/main/resources/com/ncc/aif/restricted_hypothesis_aif.shacl
src/test/java/com/ncc/aif/NistExamplesAndValidationTest.java
src/test/java/com/ncc/aif/NistTA3ExamplesAndValidationTest.java

- Incorporate AIDA-827 into releases/v1.0.  See [its PR](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/205/files) for comparison.
- Incorporate AIDA-850 into releases/v1.0.  See [its PR](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/212/files) for comparison.

Aida 832: Incorporate AIDA-827 and AIDA-850 into releases/v1.0.

---

src/main/java/com/ncc/aif/ont2javagen/OntologyGeneration.java
src/main/java/com/ncc/aif/ont2javagen/README.md
src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
src/test/java/com/ncc/aif/NistExamplesAndValidationTest.java
src/test/java/com/ncc/aif/NistTA3ExamplesAndValidationTest.java
src/test/java/com/ncc/aif/ShaclShapes.java
src/test/java/com/ncc/aif/TestUtils.java

First PR: #206
Second PR: #214

AIDA-840: Incorporate AIDA-813 into releases/v1.0.

---

FAQ.md
README.md
pom.xml

Updated POM, README, and FAQ  to v1.0.2-SNAPSHOT.

Bumped version to 1.0.2-SNAPSHOT

---

src/main/java/com/ncc/aif/ValidateAIF.java

Changes aren't from any specific PR as none encapsulated this change exclusively.
[AIDA-795](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/200) includes most of the changes: [commit](https://github.com/NextCenturyCorporation/AIDA-Interchange-Format/pull/200/commits/3b2afc1441e5a133b3ca60059e67ef5a67efebf8)

AIDA-810: Switch from OntModel to default Model for releases/v1.0

---

pom.xml

Add name, description, license, developer, scm, and distributionManagement

AIDA-862: Modify pom file to satisfy OSSRH requirements.

---

FAQ.md
README.md
pom.xml

Bumped version number to 1.0.3.

AIDA-891:  Bumped version number to 1.0.3

---

FAQ.md
README.md
pom.xml

Set AIF version to 1.0.4-SNAPSHOT.

AIDA-891b: set AIF version to 1.0.4-SNAPSHOT

---

java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
java/src/test/java/com/ncc/aif/TestUtils.java
python/aida_interchange/aida_rdf_ontologies.py
python/tests/examples.py

Added methods to create hypotheses separately from normal AIF.
Created way to validate union of hypothesis and normal AIF.
Exposed more methods in TestUtils for tests to use.

AIDA-1140: Examples of hypotheses in annotations.

---

README.md
java/README.md
java/pom.xml

Bump version to v1.1.0 in preparation for release to releases/v1.1 branch.

Bump version to v1.1.0

---

FAQ.md
README.md
docker/batch-init/README.md
docker/batch-single/README.md
java/README.md
java/pom.xml
java/src/main/java/com/ncc/aif/ThreadedValidationEngine.java
java/src/main/java/com/ncc/aif/ValidateAIF.java
java/src/main/java/com/ncc/aif/ValidateAIFCli.java
java/src/main/resources/com/ncc/aif/aida_ontology.shacl
java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
java/src/test/java/com/ncc/aif/TestUtils.java
java/src/test/java/com/ncc/aif/ValidateCLITest.java
python/aida_interchange/aida_rdf_ontologies.py
python/setup.py
python/tests/examples.py

To test, I'd suggest investigating the diffs and ensure all changes match those slated for [AIF release v1.1.0](https://nextcentury.atlassian.net/projects/AIDA/versions/12710/tab/release-report-all-issues).

Aida 1355: Merge AIF develop into master

---

java/README.md
java/pom.xml
python/setup.py

Bumped develop to v1.1.1-SNAPSHOT.

AIDA-1354b: Bumped develop to v1.1.1-SNAPSHOT

---

docker/aif-validator/scripts/main.py
java/src/main/resources/com/ncc/aif/ontologies/LDCOntologyM36
java/src/main/resources/com/ncc/aif/ontologies/LDCOwlOntologyM36

Fix M36 ontology problems (spaces).
Add environment variable to use M36 ontology instead of M18.

AIDA-1513: Changes for 1.2-SNAPSHOT.

---

java/src/main/resources/com/ncc/aif/aida_ontology.shacl
java/src/main/resources/com/ncc/aif/restricted_aif.shacl
java/src/main/resources/com/ncc/aif/restricted_hypothesis_aif.shacl
java/src/test/java/com/ncc/aif/NistExamplesAndValidationTest.java
java/src/test/java/com/ncc/aif/NistTA3ExamplesAndValidationTest.java
java/src/test/java/com/ncc/aif/ScalingTest.java
java/src/test/java/com/ncc/aif/ShaclShapes.java

Moved and renamed HypothesisClusterMembersShape.
Updated tests to account for move.
Updated tests to reflect ontology move.

AIDA-1543: Move cluster member class restriction.

---

java/pom.xml
python/setup.py

This adds the plugins required to push a release to OSSRH. You can verify that it was inadvertently but successfully published by checking out https://search.maven.org/search?q=g:com.github.nextcenturycorporation.

AIDA-865: Add release profile

---

java/src/main/resources/com/ncc/aif/aida_ontology.shacl
java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
python/aida_interchange/aifutils.py
python/aida_interchange/claim.py
python/aida_interchange/claim_component.py
python/tests/claim_example.py

@gitnordt ,
Reviewed the output claim ttl's with NIST.  Looks like we're on the same page now. If you're interested in running it let me know and I can walk you through it.  But I think all you really need to do is make sure my python and java isn't too crazy.  Let me know if you have any questions.  
Thanks!
Phi

Aida 1935 - Added claim and claim component to python

---

docker/aif-validator/Dockerfile
docker/aif-validator/scripts/main.py
java/src/main/resources/com/ncc/aif/aida_ontology.shacl
java/src/main/resources/com/ncc/aif/dwd_aif.shacl
java/src/main/resources/com/ncc/aif/ontologies/InterchangeOntology

Hi Stacey,
Tested and it appears to be working correctly. I pushed the docker to dockerhub on the develop branch (https://hub.docker.com/repository/docker/nextcenturycorp/aif_validator).  Also let teams know that things are on the develop branch till I get the NIST restriction requirements from NIST. Let me know if there's anything crazy.

Aida 1977 - Dockerize AIF Validator and updates to ontology and shacl from NIST

---

java/src/main/java/com/ncc/aif/ValidateAIFCli.java

Changed AIF to use memory model as default instead of disk model

Changed AIF to use memory model as default instead of disk model

---

java/src/main/resources/com/ncc/aif/restricted_claimframe_aif.shacl

Removed unnecessary confidence check on rdf:Statement for AssociatedKEs edge check

AIDA-2088 - removed '?statement aida:confidence ?confidence .'
